apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment120
spec:
  selector:
    matchLabels:
      app: nginx120
      tier: frontend
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx120
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment120
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx120
